DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
COMBO_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
